### ISSUE TITLE
Update to storm crawler 0.8?

### ISSUE THREAD

**Issue by w0mbat** [PopSugar/storm-crawler-extensions#22]
Will this module get updated to a newer version of storm crawler?

**Comment by w0mbat** [comment]
I will create a pull-request soon for the changes

**Comment by w0mbat** [comment]
see #23

**Comment by Chatom** [comment]
This module didn't get updated as the whole project is deprecated and I believe unmaintained.
I think that if you need to use the MicrodataFilter you should rather try to integrate it into storm-crawler directly and maintain it there.

**Comment by w0mbat** [comment]
@Chatom Ok got it - I will try to integrate it into the DigitalPebble fork of this project

**Comment by jnioche** [comment]
@w0mbat best to have your own fork, this is not a resource I intend to maintain myself. One of the strengths of SC is its modularity. Users can easily have stuff in external repos and use them as dependencies with SC
