### ISSUE TITLE
JSoupParser to use URLFilterUtil

### ISSUE THREAD

**Issue by jnioche** [PopSugar/storm-crawler-extensions#3]
I have added a utility class URLFilterUtil to simplify the filtering of URLs based on the host or domain name of the source URL. This requires the version of storm-crawler to be upgraded to 0.4 when it is released.

**Comment by GuiForget** [comment]
Talking about this... When are we releasing 0.4 ? :)

**Comment by jnioche** [comment]
See [https://github.com/DigitalPebble/storm-crawler/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.4].

**Comment by jnioche** [comment]
Not necessary now that the host filtering is a URLFilter
