### ISSUE TITLE
MicroData : update signature of configure method

### ISSUE THREAD

**Issue by jnioche** [PopSugar/storm-crawler-extensions#4]
The next release of s/c will contain 

`void configure(Map stormConf, JsonNode filterParams)`

we need to update this. 

Am not familiar with Gradle, would it make sense to declare a dependency on the latest available version of SC even if it is a SNAPSHOT one?

**Comment by GuiForget** [comment]
Yeah I already have a change ready.

**Comment by jnioche** [comment]
implemented in [https://github.com/PopSugar/storm-crawler-extensions/commit/be30c5f96267bcbbb3cc5f21543de7a3a8cf08d2]. Thanks!
